plugins {
id 'com.android.application'
}

android {
namespace "fir.tube"
compileSdk 35

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "fir.tube"  
    minSdk 29
    targetSdk 36
    versionCode 1
    versionName "1.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}
        

}


dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
}
