plugins {
id 'com.android.application'
}

android {
namespace "fir.tube"
compileSdk 35

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "fir.tube"  
    minSdk 30
    targetSdk 37
    versionCode 5
    versionName "5.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}
        

}


dependencies {
}
